FROM python:3.10-slim

# Créer un utilisateur non-root
RUN useradd -m -u 1000 user
ENV PATH="/home/user/.local/bin:$PATH"

WORKDIR /app

# Copier requirements et installer
COPY  ./api/tests/requirements-test.txt ./requirements-test.txt
RUN pip install --no-cache-dir -r requirements-test.txt

COPY --chown=user ./api/app.py .
COPY --chown=user ./api/tests/ tests/
COPY --chown=user ./api/tests/wait_for_api.py ./wait_for_api.py

USER user
EXPOSE 7860


# La ligne CMD est supprimée, car le workflow 'api-deploy.yml'
# fournit la commande d'exécution complète (lancement de l'API + pytest)

# Commande pour démarrer le serveur et exécuter les tests
#CMD ["/bin/bash", "-c", "uvicorn app:app --host 0.0.0.0 --port 7860 & python3 wait_for_api.py && pytest tests -v"]