FROM python:3.10-slim

# Créer un utilisateur non-root
RUN useradd -m -u 1000 user
USER user
ENV PATH="/home/user/.local/bin:$PATH"

WORKDIR /app

# Copier requirements et installer
COPY --chown=user ./api/test/requirements-test.txt ./requirements-test.txt
COPY --chown=user ./api/app.py .
COPY --chown=user ./api/tests/ tests/


RUN pip install --no-cache-dir --upgrade -r requirements.txt


# Exposer le port de l'API
EXPOSE 7860

# Commande pour démarrer le serveur et exécuter les tests
CMD sh -c "uvicorn app:app --host 0.0.0.0 --port 7860 & pytest tests -v"